src/book/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path('view_book', views.BookListView.as_view(), name='book_view_all.html'),
    path('book_add', views.BookCreateView.as_view(), name='book_add.html'),
    path('book_detail/<int:pk>', views.BookDetailView.as_view(), name='book_detail.html'),
    path('book_update/<int:pk>', views.BookUpdateView.as_view(), name='book_update.html'),
    path('book_delete/<int:pk>', views.BookDeleteView.as_view(), name='book_delete.html')
    ]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static
from directories import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('directories/', include('directories.urls'), name='directories'),
    path('hp/', include('homepage.urls'), name='hp'),
    path('cart/', include('cart.urls'), name='cart'),
    path('book/', include('book.urls'), name='book'),
    path('search/', include('search.urls'), name='search'),
    path('profile/', include('user_profile.urls'), name='profile'),
    path('staff/', include('staff.urls'), name='staff'),
  
]

src/search/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.urls import path, include
from search.views import search


app_name = 'search'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', search, name='search'),
   
]

src/bookshop/templates/book-shop/author/authors.html
{% extends 'base.html' %}

{% block TITLE %}Author{% endblock TITLE %}

{% block BODY %}
  {% if user.is_superuser %}
    <form action="{% url 'BookShop:add-authors' %}">
      <button class="btn btn-primary">Добавить</button>
    </form>
  {% endif %}

  <ul>
    {% for object in object_list %}
       <li>
          <a href="{% url 'search:search' %}?q={{ object.author_name }}">
             {{ object.autor_name }}  
          </a>
          {% if user.is_superuser %}
            <a href="{% url 'BookShop:update-authors' pk=object.pk %}" 
              style ="margin-left:5%">Изменить</a>

            <a href="{% url 'BookShop:delete-authors' pk=object.pk %}" 
              style ="margin: .1rem .1rem">Удалить</a>

          {% endif %}
       </li>
    
        
    {% endfor %}
 </ul>

{% endblock BODY %} 